### ISSUE TITLE
Query selectors

### ISSUE THREAD

**Issue by benjamingr** [milankinen/react-reactive-toolkit#2]
Hey, props for nailing the flow of things down the render tree - I'm about to give a talk on something similar tomorrow at a React event at Facebook and it looks like you ended up with very similar conclusions w.r.t binding to RxJS as I have (only you did it first) so first of all major props.

Second - I think the flow of data here is nice but the event handling upwards is still problematic. Querying the JSX for a className feels really ugly here. Wouldn't it be much nicer if you could get an interface that gives sugar over what you have with event callbacks? 

Currently:

``` js
// jsx
<button className="inc">++</button>

// event code
const inc$ = Observable.fromEvent(events(".inc"), "click")
    .map(() => +1)
```

Wanted: 

``` js
<button clicked={events.clicked} />
const inc$ = events.clicked.map(() => +1); 
```

I think this can be accomplished with a getter.

**Comment by milankinen** [comment]
Hi @benjamingr!

Thanks for the feedback! Also one notable thing in this project is that it isn't bound to any specific library (although examples are written with `rx`, you could easily mix whatever observable library you want) e.g.

``` javascript
import React from "react"
import R from "react.reactive"
import {render} from "react-dom"
import {Observable} from "rx"
import Kefir from "kefir"

const $app =
  document.getElementById("app")

const counter =
  Kefir.interval(100).scan(c => c + 1, 0)

const time =
  Observable.interval(1000)
    .startWith(null)
    .map(() => new Date().toTimeString())

const App = () =>
  <div>
    <R.h1>Hello Kefir {counter}!</R.h1>
    <R.p>
      Time is now {time}
    </R.p>
  </div>

render(<App  />, $app)
```

About the data flow - I've thought the very same questions many times but not managed find the optimal solution yet. You have good points, but the syntax and terms are crucial in this: `onClick`, `onChange` etc. handlers have a strong imperative smell, thus using them leads easily to non-declarative and unmaintainable code. 

Do you have more details about your approach? I'd gladly hear more about it.
